name: Launch Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código fuente
      uses: actions/checkout@v2

    - name: Clonar el repositorio irisapitester
      run: git clone https://github.com/daniel-aguilar-garcia/irisapitester.git

    - name: Levantar Docker Compose
      run: docker-compose up -d
      working-directory: ./irisapitester

    - name: Wait for Docker
      run: sleep 30

    - name: Send report to Google chat
      id: send_report_google
      run: |
        $(curl -s localhost:52773/pull_run_and_send_google)
