name: Envío de resultado por email

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código fuente
      uses: actions/checkout@v2

    - name: Clonar el repositorio irisapitester
      run: git clone https://github.com/daniel-aguilar-garcia/irisapitester.git

    - name: Levantar Docker Compose
      run: docker-compose up -d
      working-directory: ./irisapitester

    - name: Esperar a que Docker esté listo
      run: sleep 30

    - name: Realizar petición GET
      run: curl -o resultado.html http://localhost:52773/pull_and_run_tests

    - name: Leer contenido del archivo resultado.html
      id: read_file
      run: |
        content=$(cat resultado.html)
        echo "::set-output name=content::$content"

    - name: Enviar email
      run: |
        API_KEY="ODRiYmFiOTcwOGNmZGNkYTliZGJhZGQ4ZjFkM2Y3Yzg6ZTZiMGZhMmZjMjA4NjIzMzFkOGRjMDBlOWYyZjUzYTk="
        EMAIL_CONTENT=$(cat resultado.html | base64 -w 0)
        curl --location 'https://api.mailjet.com/v3.1/send' \
        --header 'Content-Type: application/json' \
        --header "Authorization: Basic $API_KEY" \
        --data-raw '{
          "Messages":[
            {
              "From": {
                "Email": "daniel@kesania.com",
                "Name": "Github"
              },
              "To": [
                {
                  "Email": "daniel@kesania.com",
                  "Name": "receiver"
                }
              ],
              "Subject": "Result test execution2",
              "TextPart": "",
              "HTMLPart": "'"$EMAIL_CONTENT"'"
            }
          ]
        }'
      env:
        EMAIL_CONTENT: ${{ steps.read_file.outputs.content }}
