name: Launch Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código fuente
      uses: actions/checkout@v2

    - name: Clonar el repositorio irisapitester
      run: git clone https://github.com/daniel-aguilar-garcia/irisapitester.git

    - name: Levantar Docker Compose
      run: docker-compose up -d
      working-directory: ./irisapitester

    - name: Wait for Docker
      run: sleep 30

    - name: Obtener valor de 'file'
      id: get_file_value
      run: echo "::set-output name=file::$(curl -s http://localhost:52773/pull_run_and_file | jq -r '.file')"

  
    - name: Enviar archivo a Google Chat
      run: |
        file_value=$(echo "${{ steps.get_file_value.outputs.file }}")
        json_data="{
          \"cards\": [
            {
              \"header\": {
                \"title\": \"Execution Test Report\",
                \"imageUrl\": \"https://example.com/imagen.png\"
              },
              \"sections\": [
                {
                  \"widgets\": [
                    {
                      \"keyValue\": {
                        \"topLabel\": \"Press to open the report file\",
                        \"content\": \"<a href='http://localhost:52773/show_report/$file_value'>Abrir en el navegador</a>\",
                        \"onClick\": {
                          \"openLink\": {
                            \"url\": \"http://localhost:52773/show_report/$file_value\"
                          }
                        }
                      }
                    }
                  ]
                }
              ]
            }
          ]
        }"
        curl -X POST -H "Content-Type: application/json" -d "$json_data" "${{ secrets.CHAT_WEBHOOK }}"
        
