name: Envío de resultado por email

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código fuente
      uses: actions/checkout@v2

    - name: Clonar el repositorio irisapitester
      run: git clone https://github.com/daniel-aguilar-garcia/irisapitester.git

    - name: Levantar Docker Compose
      run: docker-compose up -d
      working-directory: ./irisapitester

    - name: Esperar a que Docker esté listo
      run: sleep 30

    - name: Realizar petición GET
      run: curl -o resultado.html http://localhost:52773/pull_and_run_tests

    - name: Codificar contenido del archivo resultado.html a Base64
      id: encode_file
      run: |
        base64 resultado.html > resultado_base64.txt
        echo "::set-output name=base64content::$(cat resultado_base64.txt)"

    - name: Enviar email con curl
      run: |
        curl -s \
          -X POST \
          --user "${{ secrets.MJ_APIKEY_PUBLIC }}:${{ secrets.MJ_APIKEY_PRIVATE }}" \
          https://api.mailjet.com/v3.1/send \
          -H 'Content-Type: application/json' \
          -d '{
            "Messages": [
              {
                "From": {
                  "Email": "daniel@kesania.com",
                  "Name": "GithubActions"
                },
                "To": [
                  {
                    "Email": "san@kesania.com",
                    "Name": "You"
                  }
                ],
                "Subject": "Result execution!",
                "TextPart": "Report test execution",
                "HTMLPart": "",
                "Attachments": [
                  {
                    "ContentType": "text/plain",
                    "Filename": "resultado.html",
                    "Base64Content": "${{ steps.encode_file.outputs.base64content }}"
                  }
                ]
              }
            ]
          }'
      env:
        MJ_APIKEY_PUBLIC: ${{ secrets.MJ_APIKEY_PUBLIC }}
        MJ_APIKEY_PRIVATE: ${{ secrets.MJ_APIKEY_PRIVATE }}
        
      
    - name: Enviar archivo a Slack
      uses: slack/github-action@3.6.0
      with:
        channel_id: 'CI/CD'
        text: 'Aquí está el archivo resultado.html'
        file_paths: 'resultado.html'
        initial_comment: '¡Resultado HTML!'
        title: 'Resultado HTML'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
