name: Launch Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código fuente
      uses: actions/checkout@v2

    - name: Clonar el repositorio irisapitester
      run: git clone https://github.com/daniel-aguilar-garcia/irisapitester.git

    - name: Levantar Docker Compose
      run: docker-compose up -d
      working-directory: ./irisapitester

    - name: Wait for Docker
      run: sleep 30

    - name: Send test request
      run: curl -o resultado.html http://localhost:52773/pull_and_run_tests

    - name: Encode file resultado.html in Base64
      id: encode_file
      run: |
        base64 resultado.html > resultado_base64.txt
        echo "::set-output name=base64content::$(cat resultado_base64.txt)"

    - name: Send e-mail
      run: |
        curl -s \
          -X POST \
          --user "${{ secrets.MJ_APIKEY_PUBLIC }}:${{ secrets.MJ_APIKEY_PRIVATE }}" \
          https://api.mailjet.com/v3.1/send \
          -H 'Content-Type: application/json' \
          -d '{
            "Messages": [
              {
                "From": {
                  "Email": "daniel@kesania.com",
                  "Name": "GithubActions"
                },
                "To": [
                  {
                    "Email": "san@kesania.com",
                    "Name": "You"
                  }
                ],
                "Subject": "Result execution!",
                "TextPart": "Report test execution:",
                "HTMLPart": "",
                "Attachments": [
                  {
                    "ContentType": "text/plain",
                    "Filename": "resultado.html",
                    "Base64Content": "${{ steps.encode_file.outputs.base64content }}"
                  }
                ]
              }
            ]
          }'
      env:
        MJ_APIKEY_PUBLIC: ${{ secrets.MJ_APIKEY_PUBLIC }}
        MJ_APIKEY_PRIVATE: ${{ secrets.MJ_APIKEY_PRIVATE }}
  
    - name: Enviar archivo a Google Chat
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{
          "cards": [
            {
              "sections": [
                {
                  "header": "Resultado HTML",
                  "widgets": [
                    {
                      "textParagraph": {
                        "text": "Resultado HTML adjunto."
                      }
                    }
                  ]
                }
              ],
              "cardActions": [
                {
                  "actionLabel": "Descargar Resultado",
                  "onClick": {
                    "openLink": {
                      "url": "data:application/octet-stream;base64,${{ steps.encode_file.outputs.base64content }}"
                    }
                  }
                }
              ]
            }
          ]
        }' "${{ secrets.CHAT_WEBHOOK }}"
